name: pushpop
description: "A simple message push tool"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.6
  cupertino_icons: ^1.0.8
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  local_notifier: ^0.1.6
  window_manager: ^0.2.7
  win32: ^5.6.0
  tray_manager: ^0.2.3
  intl: ^0.18.0
  http: ^1.2.2
  flutter_riverpod: ^2.6.0
  flutter_client_sse: ^2.0.3
  url_launcher: ^6.3.0
  crypto: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.14.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.0.0
  hive_generator: ^1.0.0
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ic.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/i.png"
  windows:
    generate: true
    image_path: "assets/images/i.png"
    icon_size: 128 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/i.png"


flutter:
  uses-material-design: true
  assets:  
    - assets/images/app_icon.ico

